### PR TITLE
fix(matchMediaObservable): expose observable for rxjs operators

### LINKED ISSUE #125: MatchMediaObservable : Upgrade from 2.0.0-beta.1 to 2.0.0-beta.3
I tried to upgrade from 2.0.0-beta.1 to 2.0.0-beta.3 and it now breaks saying that :
`EXCEPTION: Uncaught (in promise): Error: Error in :0:0 caused by: this.media$.map is not a function TypeError: this.media$.map is not a function`

My code :

```js
constructor(@Inject(MatchMediaObservable) public media$) { }

this.media$
  .map((change: MediaChange) => { ... });
```
I looked in release notes and changelog but couldn't find anything about breaking change.

### PR DESCRIPTION
**Pull request by ThomasBurleson**
* rename token from 'MatchMediaObservable' to `ObservableMediaService`
* rename MatchMediaObservableProvider to `ObservableMediaServiceProvider`
* add method `.asObservable()` to MediaService

BREAKING CHANGE:

* use opaque token `ObservableMediateService` to inject instance of `MediaService`
* use `MediaService::asObservable()` to get instance of observable

```js
// RxJS
import 'rxjs/add/operator/map';

@Component({ ... })
export class MyComponent {
  constructor( @Inject(ObservableMediaService) media) {
    media.asObservable()
      .map( (change:MediaChange) => change.mqAlias == 'md' )
      .subscribe((change:MediaChange) => {
        let state = change ? `'${change.mqAlias}' = (${change.mediaQuery})` : ""
        console.log( state );
      });
  }
}
```

fixes #125.

### CODE REVIEW

**Comment by ThomasBurleson** [comment]
@andrewseguin - fyi.

**Comment by andrewseguin** [comment]
Presubmit looks good but you've got a fit() test in there

**Comment by ThomasBurleson** [comment]
@andrewseguin - I am changing the API. Ready tomorrow.

**Comment by ThomasBurleson** [comment]
@andrewseguin - ready not for presubmit + merge. Thx

**Comment by andrewseguin** [comment]
Change looks good to me, I'll add an LGTM. In the next PRs, it would be nice to have an LGTM ready on the PR before we send it off for presubmit/merge. Feel free to add anyone on the material2 team to review for future PRs

**Comment by andrewseguin** [comment]
Needs a small change to fix some breakage. When you import ObservableMediaService, be sure to refer to the `lib/media-query/observable-media-service.ts` file. Some are referring to `match-media.ts`

**Comment by ThomasBurleson** [comment]
@andrewseguin - I just fixed those import issues in the demos. Thx for that catch. LGTM now.

**Pull request merged**
