### PR TITLE
layoutAlign: add 'space-evenly' as main axis option

### PR DESCRIPTION
**Pull request by spottedmahn**
[https://stackoverflow.com/questions/45945938/how-to-use-space-evenly-in-flex-layout](https://stackoverflow.com/questions/45945938/how-to-use-space-evenly-in-flex-layout)

### CODE REVIEW

**Comment by spottedmahn** [comment]
I signed it!

**Comment by ThomasBurleson** [comment]
@spottedmahn 

* please rebase from `master`
* please update `layoutAlignment.demo.html with
```html
<md-radio-group [(ngModel)]="options.mainAxis" name="mainAxis" fxLayout="column">
            <md-radio-button value="">none</md-radio-button>
            <md-radio-button value="start">start (default)</md-radio-button>
            <md-radio-button value="center">center</md-radio-button>
            <md-radio-button value="end">end</md-radio-button>
            <md-radio-button value="space-around">space-around</md-radio-button>
            <md-radio-button value="space-between">space-between</md-radio-button>
            <md-radio-button value="space-evenly">space-evenly</md-radio-button>
          </md-radio-group>
```
*  Please squash your commits.

**Comment by ThomasBurleson** [comment]
@spottedmahn - please squash your commits into a single commit with title:  

`fix(api, layoutAlign): add 'space-evenly' as main axis option`.

**Comment by ThomasBurleson** [comment]
@spottedmahn - you did not squash your commits. in fact, you broke the tests for this PR. Would you like me to close this one and create a new one (with you given a shoutout credit)?

**Comment by ThomasBurleson** [comment]
Closing to create a new PR with single, clean commit.

**Comment by spottedmahn** [comment]
@ThomasBurleson I'm trying 😄 !!

I'm not ready to throw in the towel just yet.  I'm comfortable using Git in VS w/ VSTS to squash merge it but not through the command line.  This is a good opportunity for me to grow!  Hopefully it is not causing you too much noise on your side.

**Comment by spottedmahn** [comment]
Thanks @ThomasBurleson

**Pull request closed without merging**
