### PR TITLE
feat(api): add responsive API for img elements

### LINKED ISSUE #81: add new API fxSrc for responsive features Image element
Similar to responsive features in the **picture** element

```html
<picture>
  <source  media="(min-width: 650px)"    srcset="images/kitten-stretching.png">
  <source  media="(min-width: 465px)"    srcset="images/kitten-sitting.png">
  <img  src="images/kitten-curled.png"  alt="a cute kitten">
</picture>

or 

<picture>
  <source media="(min-width: 800px)"
          sizes="80vw"
          srcset="lighthouse-landscape-640.jpg 640w,
                  lighthouse-landscape-1280.jpg 1280w,
                  lighthouse-landscape-2560.jpg 2560w">
  <img src="lighthouse-160.jpg" alt="lighthouse"
       sizes="80vw"
       srcset="lighthouse-160.jpg 160w,
               lighthouse-320.jpg 320w,
               lighthouse-640.jpg 640w,
               lighthouse-1280.jpg 1280w">
</picture>

``

Enable adaptive layouts with:

```html
<img 
     fxSrc="images/kitten-curled.png" 
     fxSrc.xs="images/kitten-sitting.png"
     fxSrc.sm="images/kitten-stretching.png"
/>

<!-- Or use SrcSet to wrap image in `<picture>` with `<source>` entries -->
<img 
     [fxSrcSet]="srcSet1" 
     [fxSrcSet.gt-sm]="srcSet2"
/>
```

> see https://www.html5rocks.com/en/tutorials/responsive/picture-element/

### LINKED ISSUE #376: ImgSrcsetDirective - Support Responsive src API
1. **Overview of the Issue** 
    - ImgSrcsetDirective only support srcset.&lt;breakpoint alias&gt;. It should also support using src.&lt;breakpoint alias&gt;
    - Also, the directive should  auto-wrap the dom element inside a &lt;picture&gt;
2. **Flex-Layout version** v2.0.0-beta.9 (https://github.com/angular/flex-layout/pull/366)
3. **Motivation for or Use Case** Enhancements suggested by @ThomasBurleson 
4. **Browsers and Operating System** any
5. **Reproduce the Error** N.A
6. **Screenshots** N.A
7. **Related Issues** https://github.com/angular/flex-layout/pull/366#issuecomment-321074307
8. **Quoting @ThomasBurleson considerations**

What happens when the user does NOT wrap the img inside a picture element?
Scenario #1:

```HTML
<img style="width:auto;"
     src="https://dummyimage.com/400x200/c7c224/000.png&text=default"
     src.md="https://dummyimage.com/500x200/76c720/fff.png&text=md"
     src.sm="https://dummyimage.com/400x200/b925c7/fff.png&text=sm"
     src.lt-sm="https://dummyimage.com/300x200/c7751e/fff.png&text=lt-sm"
     src.gt-lg="https://dummyimage.com/700x200/258cc7/fff.png&text=gt-lg" >
```

In this case ^ (#1), should we auto-wrap the dom element inside a &lt;picture&gt; node?

Scenario #2:

Use tries to use the src property responsively:
```HTML
<img style="width:auto;"
     src="https://dummyimage.com/400x200/c7c224/000.png&text=default"
     srcset.md="https://dummyimage.com/500x200/76c720/fff.png&text=md"
     srcset.sm="https://dummyimage.com/400x200/b925c7/fff.png&text=sm"
     srcset.lt-sm="https://dummyimage.com/300x200/c7751e/fff.png&text=lt-sm"
     srcset.gt-lg="https://dummyimage.com/700x200/258cc7/fff.png&text=gt-lg" >
```

In this case ^ (#2), should we responsively update the src property OR should we convert these
to srcset values?

### PR DESCRIPTION
**Pull request by ThomasBurleson**
* add ImgSrcsetDirective 
  *  to inject <source> elements to support responsive images
  *  Inject a <source> element for every srcset.<breakpoint alias> in the HTML markup of an  element contained in a <picture> elemen
  *  support usages without `<picture>` parents
* add responsive API to img.src:  src.md, src.lt-lg, src.gt-xs, etc.
* repackage API classes to easily distinguish flexbox APIs and  extended responsive APIs

Closes #366, Fixes #81, Fixes #376.

### CODE REVIEW

**Comment by ThomasBurleson** [comment]
This PR uses the work (and changes and approvals) from PR #366. It adds:

*  more unit tests
*  support for responsive `img.src` APIs
*  repackaging of API classes

@benbraou - please confirm the use of your commit here in this PR. Can you also review the new additions `img-src.ts` and `img-src.spec.ts` ?
@andrewseguin - can you review these two files also ?

> Once this all looks good, let's merge ASAP as this is the LAST merge before we release Beta.9.

**Comment by andrewseguin** [comment]
`img-src.ts` and `img-src.spec.ts` look alright to me, from a naive review

**Comment by benbraou** [comment]
I am starting the review

**Comment by ThomasBurleson** [comment]
@benbraou - waiting for your response(s) before starting the merge.

**Comment by benbraou** [comment]
1. I confirm the use of your commit here in this PR
2. LGTM img-src.ts and img-src.spec.ts. It would be good however to include an example of src API in the existing picture demo. @ThomasBurleson what do you think ? I can do a PR for that if needed
3. In the current picture demo, I see the following problem:
    - If you start with large screen and then resize until small window, you will see the following javascript error (when the default breakpoint activates):
```
Uncaught TypeError: Cannot read property 'setAttribute' of undefined
    at DefaultDomRenderer2.setAttribute (platform-browser.umd.js:2859)
    at BaseAnimationRenderer.setAttribute (animation_renderer.ts:245)
    at DebugRenderer2.setAttribute (services.ts:999)
    at ImgSrcsetDirective._updateSrcsetFor (flex-layout.umd.js:3360)
    at eval (flex-layout.umd.js:3336)
    at ResponsiveActivation.eval [as _onMediaChanges] (flex-layout.umd.js:419)
    at ResponsiveActivation._onMonitorEvents (flex-layout.umd.js:281)
    at SafeSubscriber.eval [as _next] (flex-layout.umd.js:261)
    at SafeSubscriber.__tryOrUnsub (Subscriber.js:238)
    at SafeSubscriber.next (Subscriber.js:185)
}
```
The demo still works though
     - If you start with a small screen, we always get stuck with the default image (but this is due to the same error). So, in this case the demo does not work
@ThomasBurleson  Can you please confirm this issue ? I am testing with Chrome Version 60.0.3112.101 - macOS Sierra

My personal investigation:
With the new refactoring(in img-srcset.ts), we now subsribe to media query changes

```typescript
    this._listenForMediaQueryChanges(DEFAULT_SRCSET, '', (changes: MediaChange) => {
      let activatedKey = changes.matches ? DEFAULT_SRCSET + changes.suffix : DEFAULT_SRCSET;
      this._updateSrcsetFor(activatedKey);
    });
}
```
The problem is that in case we fallback to default srcset and invoke _updateSrcsetFor
```typescript
      // Identify the correct source and simply update the attribute with the new value
      let target = this._injectedSourceElements[activatedKey];
      this._renderer.setAttribute(target, DEFAULT_SRCSET, this._queryInput(activatedKey));
}
```
_injectedSourceElements has not been populated with the key srcset (as no source element is created to reflect the default src value...). So target is null and setAttribute fails. 
Maybe the simplest fix is to check if target is not null ? I tried it locally and seems to fix the problem
I hope I am not missing something and sorry if this is a false alert...

**Comment by ThomasBurleson** [comment]
@benbraou - based on your feedback and struggles with testing on `ImgSrcsetDirective`, I have removed that functionality from this PR. 

> We will keep PR #366  open for more tests, commits, and stabilizations.

**Pull request merged**
