### PR TITLE
docs: Adds note about default unit for fxFlex if none given

### PR DESCRIPTION
**Pull request by peterramsing**
Maybe I'm missing something, but this might be helpful to specify.

### CODE REVIEW

**Comment by peterramsing** [comment]
I'm not entirely sure how my changes broke the build. I'll look at it later to see what's up.

**Comment by julianobrasil** [comment]
This info is already in the docs, but buried in the [Responsive API](https://github.com/angular/flex-layout/wiki/Responsive-API). I also think it's hard to find, dispute the fact that some examples kind of suggest it.

**Comment by peterramsing** [comment]
@julianobrasil, yup, that is pretty well doc'd in the Responsive API section. I'd almost want to bring that formatting to what I did if what I wrote should even go where I put it.

**Comment by peterramsing** [comment]
@ThomasBurleson, I suppose this PR might be the tip of a documentation Iceberg. Is there any other documentation that I could help with? Are there any areas outside of #598 that I could help with?

**Comment by CaerusKaru** [comment]
Please rebase to resolve the test failure

**Comment by peterramsing** [comment]
@CaerusKaru Done.

**Pull request merged**
