### PR TITLE
chore: remove deprecated fxLayoutWrap

### PR DESCRIPTION
**Pull request by CaerusKaru**

### CODE REVIEW

**Comment by CaerusKaru** [comment]
Same error as #474

**Comment by CaerusKaru** [comment]
Blocked by #523

**Comment by ThomasBurleson** [comment]
@CaerusKaru - seems reasonable to remove verbose API when option is already provided in `fxLayout`.

**Comment by ThomasBurleson** [comment]
@CaerusKaru - while I like this. Perhaps we should deprecate this feature current HEAD and the next release and then formally remove it in two releases ?

**Comment by CaerusKaru** [comment]
From the comment in `fxLayoutWrap`, it looks like it's been deprecated at least since beta.10. But I think it could wait until we bump major to 5.0.0

**Comment by ThomasBurleson** [comment]
Yes. Let's keep this PR pending until then.

**Pull request closed without merging**
