### PR TITLE
fix(build): support Angular 4 and AOT

### LINKED ISSUE #254: Warning npm installing the latest flex-layout
### Repro steps

1.  Generate a new project with @angular/cli, e.g. ng new example
2. Install flex-layout
Expected result:
Package installs successfully.

Actual result:
Package installs with warnings:
```
➤ npm i -S @angular/flex-layout
example@0.0.0 /Users/pdejuan/projects/101/ngcourses/example
└── @angular/flex-layout@2.0.0-beta.7 

npm WARN @angular/flex-layout@2.0.0-beta.7 requires a peer of @angular/common@^2.3.5 but none was installed.
npm WARN @angular/flex-layout@2.0.0-beta.7 requires a peer of @angular/core@^2.3.5 but none was installed.
npm WARN @angular/flex-layout@2.0.0-beta.7 requires a peer of zone.js@^0.7.2 but none was installed.
```

Suggestion:
Update dependencies in the build
https://github.com/angular/flex-layout-builds/blob/master/package.json
To be updated to Angular 4.0.2

  "peerDependencies": {
    "@angular/common": "^2.3.5",
    "@angular/core": "^2.3.5",
    "rxjs": "^5.0.1",
    "zone.js": "^0.7.2"
  }

### PR DESCRIPTION
**Pull request by crisbeto**
* Bumps all of the `@angular` dependencies to 4 and Material to 2.0.0-beta.3.
* Fixes a few linter errors.
* Fixes an issue that prevented AoT from working under Angular 4.
* Moves away from a few of the APIs that were deprecated in Angular 4.
* Fixes issues with the testing setup which prevented the module from compiling with Angular 4.
* Fixes the demo app not working properly due to the Material theme not being included correctly.

BREAKING CHANGE:

These changes to **@angular/flex-layout** will require Angular v4.x and will **not** be compatible with Angular v2.x.

Fixes #254, #236, #227.

### CODE REVIEW

**Comment by jelbourn** [comment]
Presubmit error:
```
	TypeError: _this._renderer.setStyle is not a function
```

**Comment by crisbeto** [comment]
That looks weird @jelbourn, it works for me locally. Also I did the same logic for Material 2 when I was migrating to the new renderer.

**Comment by jelbourn** [comment]
@crisbeto Yeah, I'm not sure why this error is occurring. It only happens in one project, the rest all pass. I'll try to investigate whether they're doing something weird.

**Comment by ThomasBurleson** [comment]
@kara - we really need to get this merged asap!

**Comment by kara** [comment]
We are looking into a related Google test failure now. Working as fast as
we can :) promise it will be in once we can get tests passing.

**Pull request merged**
