### PR TITLE
fix(sass): update stylesheet with correct keys

### PR DESCRIPTION
**Pull request by CaerusKaru**

### CODE REVIEW

**Comment by fabiocarneiro** [comment]
Nice!

**Comment by mackelito** [comment]
When can we expect this to be released? I'm really eager to try out the overlapping keys :)

**Comment by CaerusKaru** [comment]
It’ll be included in the next beta release, currently tracking for mid-February.

**Comment by YakirSmartag** [comment]
Hi, does anyone knows when the next version will be released (bate.24)? I see little activity in this repository

**Comment by jarekw87** [comment]
@CaerusKaru please fix the mixin:

```
@mixin layout-bp($bp) {
  @if map-has-key($breakpoints, $bp) {
    $min: map-get(map-get($breakpoints, $bp), begin);
    $max: map-get(map-get($breakpoints, $bp), end);
    @media (min-width: $min) and (max-width: $max) { @content;  background-color: green;}
  }
  @else if map-has-key($overlapping-gt, $bp) {
    $min: map-get($overlapping-gt, $bp); // $breakpoints change to $overlapping-gt
    @media (min-width: $min) { @content; background-color: pink; }
  }
  @else if map-has-key($overlapping-lt, $bp) {
    $max: map-get($overlapping-lt, $bp); //$breakpoints change to $overlapping-lt
    @media (max-width: $max) { @content; background-color: blue;}
  }
}
```

When can we expect this to be released? :)

**Pull request merged**
