### PR TITLE
Fix SSR build: check null _document.defaultView

### PR DESCRIPTION
**Pull request by dodongphure**
Fix https://github.com/angular/flex-layout/issues/1324

### CODE REVIEW

**Review by CaerusKaru — APPROVED** [review]

**Comment by CaerusKaru** [comment]
For some reason SauceLabs is deciding to flake out on every run. I'll investigate this and try to get it to pass later this week. Thanks for the contribution!

**Comment by CaerusKaru** [comment]
@dodongphure ok CI should be resolved now, can you rebase from master?

**Comment by dodongphure** [comment]
@googlebot I consent.

**Comment by dodongphure** [comment]
@googlebot I consent

**Comment by CaerusKaru** [comment]
@dodongphure Your PR is in a bad state; your rebase was unsuccessful it looks like. Please make sure you have pulled from origin/master and rebased instead of just doing git pull.

**Comment by dodongphure** [comment]
Sorry close this and opened new pull https://github.com/angular/flex-layout/pull/1337.

**Pull request closed without merging**
