### PR TITLE
Fix RegExp Issue in older versions of Safari

### PR DESCRIPTION
**Pull request by swftvsn**
Error is: TypeError: Cannot supply flags when constructing one RegExp from another.  

Discussion here: https://stackoverflow.com/questions/37919802/regex-created-with-constructor-not-working-with-safari

### CODE REVIEW

**Comment by CaerusKaru** [comment]
I just tested that expression on both Safari 10 and 11. The issue was opened in 2016 and looks like it's been resolved in the latest two versions of Safari, which is all we support.

Thanks for the contribution, but it hardly seems necessary now.

**Comment by swftvsn** [comment]
That's very unfortunate, as that is the single thing breaking safari 9 and older support :/ It's also a safe change, and the RegExp constructor does nothing but adds clutter and decreases performance. (As two regexps are constructed.)

**Comment by swftvsn** [comment]
Hmm, I probably then have to fork & support a separate version for us.

**Comment by CaerusKaru** [comment]
Alright, you've convinced me. I'll run this up to @ThomasBurleson but if it's minimal code and allows for Safari 9 support to be added back, I'm for it.

**Comment by CaerusKaru** [comment]
@swftvsn please add a comment above the regex change explaining why it’s necessary

**Comment by swftvsn** [comment]
Is the comment I added enough?

**Comment by CaerusKaru** [comment]
@swftvsn Looks good, but @ThomasBurleson might suggest edits before it gets merged

**Comment by CaerusKaru** [comment]
@swftvsn Looks like you've got some linting errors that need to be resolved. Other than that, tests look good.

**Comment by swftvsn** [comment]
Fixed tslint errors.

**Comment by CaerusKaru** [comment]
@swftvsn Pro tip: Just linking https://stackoverflow.com/questions/37919802 will resolve to the full URL

**Comment by swftvsn** [comment]
Thanks!

**Comment by ThomasBurleson** [comment]
@swftvsn - please squash your commits. Thank you for this fix.

**Comment by swftvsn** [comment]
Haha, seems that I don't know how to do a squash. If I understand correctly the user interface of github allows this as part of the merge. However, I'm not allowed to merge, so I tried to pull my branch, and then do  

```
git rebase -i HEAD~4
git pull
git push
```
But I think it's worse now. So, can you provide any assistance what should I do with that branch next? And how do I provide CLA. The committer is me.

**Pull request merged**
