### PR TITLE
update(build): update to Angular 4 dependencies.

### LINKED ISSUE #236: angular4 aot compilation
Hi all I've just update to angular4 but now it break when the application is render.
What I'm doing is using custom media query.
This is my code:

```ts
export const customBreakPoints: BreakPoint[ ] = [
    {
        alias: 'small',
        suffix: 'Xs',
        overlapping: false,
        mediaQuery: 'screen and (max-width: 319px)'
    },
    {
        alias: 'small',
        suffix: 'GtXs',
        overlapping: true,
        mediaQuery: 'screen and (max-width: 319px)'
    },
    {
        alias: 'mobile',
        suffix: 'Sm',
        overlapping: false,
        mediaQuery: 'screen and (min-width: 320px) and (max-width: 767px)'
    },
    {
        alias: 'mobile',
        suffix: 'GtSm',
        overlapping: true,
        mediaQuery: 'screen and (min-width: 320px) and (max-width: 767px)'
    },
    {
        alias: 'tablet',
        suffix: 'Md',
        overlapping: false,
        mediaQuery: 'screen and (min-width: 768px) and (max-width: 1023px)'
    },
    {
        alias: 'tablet',
        suffix: 'GtMd',
        overlapping: true,
        mediaQuery: 'screen and (min-width: 768px) and (max-width: 1023px)'
    },
    {
        alias: 'desktop',
        suffix: 'Lg',
        overlapping: false,
        mediaQuery: 'screen and (min-width: 1024px)'
    },
    {
        alias: 'desktop',
        suffix: 'GtLg',
        overlapping: true,
        mediaQuery: 'screen and (min-width: 1024px)'
    },
    {
        alias: 'desktop',
        suffix: 'Xl',
        overlapping: false,
        mediaQuery: 'screen and (min-width: 1024px)'
    }
];

@NgModule({
    bootstrap: [AppComponent],
    imports: [
        BrowserModule,
        HttpModule,
        FlexLayoutModule
    ],
    declarations: [
        AppComponent
    ],
    providers: [
...
        {provide : BREAKPOINTS, useValue: customBreakPoints}
    ]
})
export class AppModule {
    constructor() {

    }
}
```
I did something wrong or something happen with angular4?
thanks

### PR DESCRIPTION
**Pull request by jrgleason**
Still waiting on the following...

https://github.com/angular/tsickle/issues/453

But once that is resolved this should work. Tested locally and the tests pass.

Fixes #236

### CODE REVIEW

**Comment by jrgleason** [comment]
I signed the CLA whenever it gets approved

**Comment by ThomasBurleson** [comment]
@jrgleason - I was getting the exact same error during a brief attempt to upgrade to ng 4.x. Let's see what happens with you efforts ^.

**Comment by ThomasBurleson** [comment]
@jrgleason - can you squash your commits plz. Also please use this for your commit message:

`update(build): update to Angular 4 dependencies.`

> Btw, what do you need from angular/tsickle#453?

**Comment by ThomasBurleson** [comment]
@mmalerba - can you review this PR? And the associated hack/fix in angular/tsickle#453?

**Comment by jrgleason** [comment]
@ThomasBurleson I wasn't sure how to properly squash since I had already merged to my forked master (So I didn't think interactive rebase would work). If we could take that off line somehow I would be more than happy to accommodate. Sorry, I am just a plebeian when it comes to Git

**Comment by jrgleason** [comment]
@cla/Google What does that mean I made all the changes

**Comment by mmalerba** [comment]
I think it's referring to b2107f9610da5a20ab8a634e5221f95fa1a8e172, we can just ignore the message and merge when this is ready

**Comment by ThomasBurleson** [comment]
Will be fixed with #255

**Pull request closed without merging**
