### PR TITLE
build: update rxjs operators and jasmine 

### LINKED ISSUE #519: Peer Dependency Error With FlexLayout On Angular5
#### Bug, feature request, or proposal:
I get peer dependency error while doing npm install of flex-layout

#### What is the expected behavior?
Should be able to install the flex-layout without any dependency error.

#### What is the current behavior?
Throws peer Dependency error.

#### What are the steps to reproduce?
Providing a StackBlitz (or similar) is the *best* way to get the team to see your issue.

*  [StackBlitz starter](https://goo.gl/y38GUZ) using latest `npm` nightly release: 
Just create a brand new Angular 5 app. then do npm install of flex-layout
"@angular/flex-layout": "^2.0.0-beta.10-4905443"

#### What is the use-case or motivation for changing an existing behavior?
I want to use Angular 5 with flexlayout

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular 5, Angular Material 5

#### Is there anything else we should know?

HERE BELOW ARE THE ERROR LOGS: 
Now it appears to be warning.. but when I deploy to my cloud environment it throws error.

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules\ch
okidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@
1.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"}
)
npm WARN @angular/flex-layout@2.0.0-beta.10-4905443 requires a peer of @angular/
core@~4.4.4 but none was installed.
npm WARN @angular/flex-layout@2.0.0-beta.10-4905443 requires a peer of @angular/
common@~4.4.4 but none was installed.
npm WARN codelyzer@3.2.2 requires a peer of @angular/compiler@^2.3.1 || >=4.0.0-
beta <5.0.0 but none was installed.
npm WARN codelyzer@3.2.2 requires a peer of @angular/core@^2.3.1 || >=4.0.0-beta
 <5.0.0 but none was installed.
npm WARN @walmart/prcui@0.0.8 No license field.

### PR DESCRIPTION
**Pull request by CaerusKaru**
Incorporates PR #474 and updates rxjs to latest best practices

Fixes #519, #508, #533

### CODE REVIEW

**Comment by CaerusKaru** [comment]
Passes all tests except the Quantum issue plaguing the other builds.

cc @ThomasBurleson

**Comment by fbascheper** [comment]
It would be great if you could update this PR for Angular 5.1 and cdk 5.0.0 (stable) which were released tonight.

**Comment by CaerusKaru** [comment]
@fbascheper Added

**Comment by ThomasBurleson** [comment]
Merged with SHA 62457a597244a9.

> Super... super helpful.  Great work Adam!

**Pull request closed without merging**
