### PR TITLE
chore: update to 15.0.0-beta.42 with changelog

### PR DESCRIPTION
**Pull request by CaerusKaru**

### CODE REVIEW

**Comment by CaerusKaru** [comment]
This will be the last full release of Flex Layout, barring any security updates that may require updates, consistent with the new LTS policy.

**Comment by jpike88** [comment]
seems good to me. when are you planning on releasing?

**Comment by CaerusKaru** [comment]
We're currently blocked on a bug fix in the framework. ETA I got on that was Wednesday.

**Comment by Dzivo** [comment]
This will help us migrate on time thanks for the support its a shame such a good library is dying

**Comment by Dzivo** [comment]
any news on this waiting eagerly :)

**Comment by Dzivo** [comment]
any news on this waiting eagerly!

**Comment by CaerusKaru** [comment]
Quick update before the weekend: we've resolved all of the CI changes except for SSR tests, which need a light refactor with changes to `@ngtools/webpack`. @alan-agius4 are working to unblock this, but it likely won't happen, and certainly won't be published, until early next week. I apologize for the delay in the meantime.

**Comment by michaelfaith** [comment]
Thanks to you both for the hard work.

**Comment by ivanpolish5** [comment]
Any news on this ?

**Comment by Dzivo** [comment]
We are kinda blocked until this is realized so we would vary much like to know when this could happen too i see others are waiting for this

**Comment by ajtowf** [comment]
"chore" soon a month, is the team alive?

**Comment by blogcraft** [comment]
> "chore" soon a month, is the team alive?

What a useful contribution of yours...

**Comment by Dzivo** [comment]
@blogcraft for the amount of work thats been done this shouldnt be under @angular namespace

**Comment by blogcraft** [comment]
> @blogcraft for the amount of work thats been done this shouldnt be under @angular namespace. Its good that it is going to be obsolete but we still need time to migrate projects.

1.- That is no reason to be rude.
2.- You can always force your npm install if upgrading is so important until v15 of flex-layout is available.
3.- Since the announcement you could have already replaced flexlayout with an alternative. I did it in 3 of my projects with ~ 4700 fx attributes each.

**Comment by jpike88** [comment]
@blogcraft what alternative did you use?

**Comment by Dzivo** [comment]
@blogcraft if it is that easy why is there no migration tools developed. I know why because its not that easy.

**Comment by Dzivo** [comment]
Also we are not rude we are just stating the facts

**Comment by blogcraft** [comment]
> @blogcraft if it is that easy why is there no migration tools developed. I know why because its not that easy.

What tools? The library was never fully adopted by angular team (this has been always public knoledge) and never left the beta, and you expect tooling? Come on, be serious.

Adopting this library and migrating from it is your responsibility only. You can take it "as is" or not take it at all and use an alternative. You are not entitled to anything and being obnoxious in every issue and pr demanding speed from the library owners and contributors IS being rude.

**Comment by Dzivo** [comment]
Prefixing library name with @angular and not doing the work so that you can feel important GJ egomaniac

**Comment by CaerusKaru** [comment]
We are actively looking into this, but there have been other things that have come up in the meantime that took priority. We hope to resolve this by EOW. In the meantime, I am locking conversation here as we are bordering very close on several CoC violations.

**Comment by CaerusKaru** [comment]
Quick update here: we've found the last build failure and corrected it. And by we, I mean 100% @alan-agius4. Once we clear this, we hope to cut a release. Unfortunately, many of the team (myself included) are approaching holidays and time off. Our goal is to get this out ASAP but it may be a little while longer.

**Pull request merged**
