### PR TITLE
feat(demo-app): use Angular CLI to build demo and universal apps

### LINKED ISSUE #568: build: convert demo-app and universal-app to use Angular CLI

### LINKED ISSUE #579: feat(demo-app): add SSR

### PR DESCRIPTION
**Pull request by CaerusKaru**
* Add CLI functionality to demo-app and universal-app
* Update CI tasks to use the CLI instead of building manually

Fixes #568 
Fixes #579

### CODE REVIEW

**Comment by ThomasBurleson** [comment]
@CaerusKaru - At this point, I wonder if we should be using the Nx mono-respository approach to manage multiple apps and libs?

**Comment by ThomasBurleson** [comment]
@CaerusKaru - can you rebase with latest from origin:master ?

**Comment by CaerusKaru** [comment]
@ThomasBurleson should be good to go 👍

**Comment by CaerusKaru** [comment]
Closed by https://github.com/angular/flex-layout/commit/eda12c382c9ea2cc959ec27252b90c6f052a1fba

**Pull request closed without merging**
