### PR TITLE
fix(media-query): fix #187, fixed for platform-server/universal

### LINKED ISSUE #187: Using flex-layout with Angular Universal
From my limited knowledge of Node, I gather that anything referencing `Document` or `Window` will throw a server-side error.

That said, I'd like to incorporate flex-layout into my Angular Universal app. Is that possible? My initial attempt (simply following the readme) throws the following error:

> ReferenceError: document is not defined

### PR DESCRIPTION
**Pull request by ardatan**
Now it gets document object from platform-browser by DI instead of global.

### CODE REVIEW

**Comment by ardatan** [comment]
I signed it!

**Comment by aparraga** [comment]
Please approve this guy!!!!!

**Comment by ThomasBurleson** [comment]
@aparraga - testing is in-progress.

**Comment by ThomasBurleson** [comment]
Closing. See PR #353

**Comment by aparraga** [comment]
When do you expect to release this guy?

**Comment by ThomasBurleson** [comment]
Beta.9 should be released within the next 10 days... Dependent on 1-3 critical bug fixes remaining.

**Pull request closed without merging**
