### PR TITLE
fix(fxFlex): fix non-wrapping behavior and default fxFlex value

### LINKED ISSUE #314: Column Layout Breaks in IE11
I opened a similar issue earlier this year about this. It was closed as it was a question, but it wasn't: I really think it's a bug, or, at least, an unforseen behavior in IE11. A column layout is working very diferent in IE11 and in Chrome. In fact it seems it is broken in IE11, as you can see in the two images bellow.

In IE11 the item in a `fxLayout="column"` container aparently collapses if you do both of this simultaneously:

- don't specify a height for the container;
- use `fxFlex` attribute in the contained items without a fixed height: it's not possible to leave it empy - just `fxFlex` -  or set a percentage value - for example `fxFlex="40%"` or `fxFlex="40"`. 

I think, in this case, in IE11, the behavior should be the same as the` fxFlex="nogrow"` option, as it is in other browsers.

plunker: https://plnkr.co/edit/zGMk1PaG5lCGsx2YAp79?p=preview

## **Chrome:**
image

## **IE11:**
image

### LINKED ISSUE #338: property:flex parsing incorrect value `1e-09px;`
property:flex parsing incorrect value `1e-09px;`  
flex

Googling 1e-09 seems to be some kind of scientific notation, and can be see as a % , / in some code out there.

`1 n  1E-09
1 µ  1E-06
1 m  1E-03
1    1
1 k  1E+03
1 M  1E+06
1 G  1E+09`

### LINKED ISSUE #481: Responsive Flex Layout Chrome Bug
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
When moving from row to column layout, controls should stack appropriately

#### What is the current behavior?
In Chrome, when transitioning from row to column layout with an element that has a nested column layout, all of the elements merge onto the same line.

##### Examples  

*Chrome at gt-md*  
chrome-gt-md  

*Chrome at lt-lg*  
chrome-lt-lg  

*Firefox at lt-lg*  
firefox-lt-lg  

#### What are the steps to reproduce?
[Repro](https://stackblitz.com/edit/angular-flex-layout-seed-dwwepm)  
*All of the relevant markup is in test.component.html*

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Tested with the following:
Angular 4.4.4
Material 2 beta 12
flex-layout 2 beta 10

#### Is there anything else we should know?
While the following causes the mess in Chrome, but works in Firefox and Edge:  

``` html
<div fxFlex fxLayout="column" fxLayoutAlign="start stretch">
```

The following causes the intended behavior to work in all browsers:  

``` html
<div fxLayout="column" fxLayoutAlign="start stretch" [ngStyle.gt-md]="{'flex': '1 1 auto'}">
```

### LINKED ISSUE #544: sticky footer issue with flex-basis
#### Bug, feature request, or proposal:
Checking my app on IE10-11 uncovered I was see an issue with my sticky footer. It was not sticky, but just say under the content block positioned above:
```
+site(fxLayout="column" fxFlex)
  |- header
  |- content(fxFlex)
  |- footer
==white-space==
```
So I went back to the article written by Philip Walton a couple of years ago, https://philipwalton.com/articles/normalizing-cross-browser-flexbox-bugs/, and implemented his fix.

However, I was a bit puzzled that this fix is still required nowadays.
So I was wondering if we still need to do this:

```
+site(fxLayout="column" fxFlex) --> add height: 100%
  |- header  --> add flex-shrink: 0
  |- content(fxFlex)  --> add flex: 1 0 auto
  |- footer -->add flex-shrink: 0
```
Only if I add the `flex:1 0 auto` to the content block, will it work fine in Chrome. I am actually overriding fxFlex at this moment.

#### What is the expected behavior?
Header at top, content stretched and footer sticky at the bottom.

#### What is the current behavior?
In IE10-11 footer is not sticky at bottom. When adding height 100% to `site`, then Chrome will squeeze the content block so that everything will fit. Fix on, break the other and vice versa.

### LINKED ISSUE #666: bug(fxFlex): flex basis should only be set to width value when wrapping
Currently the flex-basis is set to the value of the width when present as a fix for wrapping in older versions of Safari. However, this throws off ordinary flex values when not wrapping (and is not needed when not wrapping).

Need a partial revert of the recent PR to fix this, with a patch that detects wrapping

### PR DESCRIPTION
**Pull request by CaerusKaru**
* Set the non-wrapping behavior for fxFlex to be 100% instead of
  the width/height value
* Set the default value for fxFlex to auto for column and 0% for
  row instead of 1e-9px

Fixes #666 
Fixes #481 
Fixes #544 
Fixes #338 
Fixes #314

### CODE REVIEW

**Comment by CaerusKaru** [comment]
Note: confirmed issue with IE11 by removing the hack. Will consult Flexbugs and try to come up with an alternative that meets all requirements.

**Comment by CaerusKaru** [comment]
Fixed the default value and officially unblocked

**Comment by ThomasBurleson** [comment]
rebase this one also plz @CaerusKaru

**Comment by CaerusKaru** [comment]
@ThomasBurleson done

**Pull request merged**
