### PR TITLE
feat(api): add responsive support for ngClass and ngStyle

### PR DESCRIPTION
**Pull request by joanllenas**
@ThomasBurleson - The new PR is ready for reviewing

### CODE REVIEW

**Comment by joanllenas** [comment]
btw, I figured out what the issues were, hence the passing build.
I messed up my commits in the previous PR, and I couldn't even find what was wrong...

**Comment by ThomasBurleson** [comment]
@joanllenas - Let me add some unit tests and this will be a GREAT addition to the library. Nice work sir!

**Comment by joanllenas** [comment]
@ThomasBurleson - perfect! thanks for your time and guidance.

**Comment by ThomasBurleson** [comment]
@joanllenas - great addition to this library. Thx again.

**Comment by d3viant0ne** [comment]
@joanllenas - Playing with this in one of my projects now, great addition.

**Comment by joanllenas** [comment]
Thanks, @d3viant0ne :)

**Pull request merged**
