### PR TITLE
Improve flex css prefixes

### PR DESCRIPTION
**Pull request by karlhaas**
With the following changes the layout of our application works in iOS8

### CODE REVIEW

**Comment by ThomasBurleson** [comment]
@karlhaas - you will need to sign the Google CLA before any merges can occur.

**Comment by karlhaas** [comment]
When I follow the link it tells me "It looks like you've already signed this CLA. If you'd like to edit your contact information, you may do so below."

**Comment by ThomasBurleson** [comment]
@karlhaas - nice work sir!

**Comment by ThomasBurleson** [comment]
@karlhaas - plz squash your commits.

**Comment by karlhaas** [comment]
@ThomasBurleson commits squashed

**Comment by ThomasBurleson** [comment]
@karlhaas  - We are concerned about some performance impacts with this PR.

*  This PR was for iOS8 ? Did this address and any other issues
*  I do not see an Github issue associated with this btw.

**Comment by karlhaas** [comment]
@ThomasBurleson for our application (feedbackr.io) it is very important to support as many devices as possible. According to http://caniuse.com/#feat=flexbox still many browsers need css prefixes for flex.
iOS8 is just one example which I used to test the changes.

Another option (which we don't really want) would not to use flex layout and material for this part of the application.

Could you provide some information regarding the performance impacts? Maybe we can provide a better solution.

**Comment by ThomasBurleson** [comment]
@karlhaas  - see https://github.com/angular/flex-layout/issues/282.

**Pull request merged**
